# -*- coding: utf-8 -*-
"""PRODIGY_GA_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FwUdFdDJ2y93Kwp65b0G-jjKzv9GkYYF
"""

import random

text = """
I love coding
I love python
I love DSA
I enjoy problem solving
"""
words = text.split()
print(words)

markov_dict = {}
for i in range(len(words)-1):

    current_word = words[i]

    next_word = words[i+1]

    if current_word not in markov_dict:
        markov_dict[current_word] = []

    markov_dict[current_word].append(next_word)

import random

def generate_text(training_text, start_word, length=10):

    words = training_text.split()

    markov_dict = {}

    for i in range(len(words)-1):

        current_word = words[i]
        next_word = words[i+1]

        if current_word not in markov_dict:
            markov_dict[current_word] = []

        markov_dict[current_word].append(next_word)
    if start_word not in markov_dict:
            return "Start word not found in training text"


    current_word = start_word

    result = [current_word]

    for i in range(length-1):

        if current_word not in markov_dict:
            break

        next_word = random.choice(
            markov_dict[current_word]
        )

        result.append(next_word)

        current_word = next_word

    return " ".join(result)

print(
    generate_text("I")
)

!pip install gradio

import gradio as gr

def markov_generator(
    training_text,
    start_word
):

    return generate_text(
        training_text,
        start_word
    )

demo = gr.Interface(

    fn=markov_generator,

    inputs=[

        gr.Textbox(
            lines=8,
            label="Training Text"
        ),

        gr.Textbox(
            label="Starting Word"
        )

    ],

    outputs=gr.Textbox(
        label="Generated Text"
    ),

    title="Markov Chain Text Generator",

    description=
    "Generate text using Markov Chains"

)

demo.launch(share=True)

